Use pydantic submodels for finer settings parsing
geobeyond/fastflows pull request #118
Opened 2022-12-09 16:29 UTC by ricardogsilva

This PR modifies the main fastflows configuration in order to take advantage of pydantic submodels.

The approach taken is to extend the main `FastflowsSettings` class that inherits from [pydantic.BaseSettingsl](https://docs.pydantic.dev/usage/settings/) with additional pydantic submodels for handling of more complex settings, like prefect, logging, etc.

In order to make it possible to define values from the environment, this implementation also makes use of pydantic's `env_nested_delimiter` setting, allowing deeply nested configuration values to be specified as env variables using a double underscore notation, as in `PREFECT__STORAGE__NAME="something"`.

Most default settings are also modified in order to reflect a local development environment, as opposed to the previous values, which implied a docker-centric default. This is part of an on-going effort to make development of fastflows less complex - Note that the docker-centric dev environment is still achieved by shifting the conf values from being default in fastflows to being explicitly set in the docker-compose files, and that is also included in this PR.

The proposed implementation allows more explicit and finer grained validation for settings like the configuration of the prefect `remote-filesystem` storage blocks, which require additional user, secret, endpoint_uris. It can now be specified like this (note the double underscore notation):

```
PREFECT__STORAGE__BLOCK_TYPE="remote-file-system"
PREFECT__STORAGE__BASE_PATH="s3://test-bucket"
PREFECT__STORAGE__KEY="some-user"
PREFECT__STORAGE__SECRET="some-password"
PREFECT__STORAGE__ENDPOINT_URL="http://nginx:9000"
```

When using a remote file system for the prefect storage, the aforementioned configuration values now become mandatory, and are checked by pydantic.

This PR also makes use of pydantic's support for `Union` types, which allows a richer definition of values that may or may not be mandatory, depending on the underlying prefect config (for example, if using a `local-filesystem` storage we do not need the settings for the remote filesystem to be provided.

```
PREFECT__STORAGE__BLOCK_TYPE="local-file-system"
PREFECT__STORAGE__BASE_PATH="/somewhere/where/storage/is/being/used"
```

The current PR also removes two `.env` files from this repo:

- `docker/.env` is removed in favor of keeping the environment variables defined in the docker-compose file
- `.env` is removed and left to each individual dev to implement. A `dev-env-sample.env` file is provided instead

2022-12-09 16:38 UTC, ricardogsilva commented
@francbartoli seems like I need to update some tests, but I think you can review nonetheless

2022-12-12 17:53 UTC, ricardogsilva commented
@francbartoli rebased and fixed tests

2022-12-12 19:45 UTC, francbartoli requested changes

2022-12-12 19:45 UTC, francbartoli commented on docker/kube-infra/fastflows.yaml
> +            - name: UVICORN__PORT
since we ship the `fastflows` CLI that starts the server then it makes sense to call the variable with the `FASTFLOWS` word

2022-12-12 19:45 UTC, francbartoli commented on fastflows/cli/utils.py
>  def process_parmas_input_as_a_comma_separated_string(params: str) -> dict:
there is a typo in the function name

2022-12-12 19:45 UTC, francbartoli commented on fastflows/config/app.py
> +    UVICORN: _UvicornSettings = _UvicornSettings()
Now I understand you'd like to handle this set of settings as a dependency

2022-12-12 19:45 UTC, francbartoli commented on fastflows/core/catalog/cache.py
> +            os.makedirs(settings.FLOWS_HOME, exist_ok=True)
Can we use the `pathlib` module instead of the `os`?

2022-12-13 09:41 UTC, ricardogsilva commented on fastflows/cli/utils.py
>  def process_parmas_input_as_a_comma_separated_string(params: str) -> dict:
not sure I understand what you mean, but if you are referring to the function that shows up on line 11, then that is not in scope of this PR - I didn't touch it. I can change it later though.

If that is not it, please clarify :wink:

2022-12-13 09:42 UTC, ricardogsilva commented on fastflows/core/catalog/cache.py
> +            os.makedirs(settings.FLOWS_HOME, exist_ok=True)
Sure, it is just that I tried to change as little actual application logic as possible with this PR, focusing more on the changes that relate to how settings are defined. I can make the change to use `pathlib`, but perhaps in another PR? Let me know how you prefer

2022-12-13 09:47 UTC, ricardogsilva commented on fastflows/config/app.py
> +    UVICORN: _UvicornSettings = _UvicornSettings()
Does this mean your comment above about `UVICORN__PORT` becomes irrelevant then?

I originally added a mandatory prefix of `FASTFLOWS__` to all settings (so they were defined via env like _e.g_ `FASTFLOWS__UVICORN__PORT`. Then I thought this was maybe too verbose, so I made the prefix optional (we already had some stuff like that for defining the env).

I think having the optional prefix should be enough to cover most cases, but let me know how you'd prefer it to be, if needed

2022-12-13 09:47 UTC, ricardogsilva commented on docker/kube-infra/fastflows.yaml
> +            - name: UVICORN__PORT
Please see my comment below

2022-12-13 10:55 UTC, ricardogsilva commented on fastflows/core/catalog/cache.py
> +            os.makedirs(settings.FLOWS_HOME, exist_ok=True)
Please see #123, which performs this change for the whole codebase

2022-12-13 11:14 UTC, francbartoli commented on fastflows/cli/utils.py
>  def process_parmas_input_as_a_comma_separated_string(params: str) -> dict:
Nope, it was just `parmas ` to be amended in the name to `params `

2022-12-13 11:15 UTC, francbartoli commented on fastflows/config/app.py
> +    UVICORN: _UvicornSettings = _UvicornSettings()
Yep, this makes the previous not relevant

2022-12-13 14:16 UTC, ricardogsilva commented on fastflows/cli/utils.py
>  def process_parmas_input_as_a_comma_separated_string(params: str) -> dict:
I've made an additional commit to fix these names

2022-12-13 14:19 UTC, ricardogsilva commented
@francbartoli, addressed review comments. How does it look now?

2022-12-13 14:26 UTC, francbartoli approved these changes

2022-12-13 14:26 UTC, merged