update prefect to 2.2.0 & fix integration & cli tests
geobeyond/fastflows pull request #50
Opened 2022-08-29 15:07 UTC by xnuinside

2022-08-30 16:19 UTC, francbartoli requested changes

2022-08-30 16:19 UTC, francbartoli commented on fastflows/core/catalog/catalog.py
> +        full_flow_path = os.path.join(cfg.FLOWS_HOME, f"{flow_file_name}.py")
Why are we mixing `os` and `pathlib` over here?

2022-08-30 16:20 UTC, xnuinside commented on fastflows/core/catalog/catalog.py
> +        full_flow_path = os.path.join(cfg.FLOWS_HOME, f"{flow_file_name}.py")
Bad habit ) sorry I will change to pathlib

2022-08-31 09:34 UTC, xnuinside commented on fastflows/core/catalog/catalog.py
> +        full_flow_path = os.path.join(cfg.FLOWS_HOME, f"{flow_file_name}.py")
updated @francbartoli

2022-08-31 09:39 UTC, francbartoli approved these changes

2022-08-31 09:39 UTC, merged